package com.eight.alogger;

import android.app.Notification;
import android.app.PendingIntent;
import android.app.Service;
import android.content.Intent;
import android.content.IntentFilter;
import android.os.IBinder;
import android.util.Log;

import androidx.annotation.Nullable;
import androidx.core.app.NotificationCompat;

public class LogService extends Service {
    private static final String TAG = LogService.class.getName();

    private static final int NOTIFY_ID = AlogApplication.getNotificationId();


    private MyBroadcastReceiver receiver;

    @Override
    public void onCreate() {
        super.onCreate();
        PendingIntent contentIntent = PendingIntent.getActivity(this, AlogApplication.getRequestCode(), new Intent(this, MainActivity.class), PendingIntent.FLAG_IMMUTABLE);
        Notification notification = new NotificationCompat.Builder(this, AlogApplication.NOTIFY_CHANNEL_ID_SERVICE)
                .setSmallIcon(R.drawable.cloud)
                .setContentTitle("Log service")
                .setContentText("Log Service foreground service is running")
                .setForegroundServiceBehavior(NotificationCompat.FOREGROUND_SERVICE_IMMEDIATE)
                .setContentIntent(contentIntent)
                .build();

        startForeground(NOTIFY_ID, notification);

        Log.i(TAG, "onCreate: LogService");
        receiver = new MyBroadcastReceiver();
        IntentFilter filter = new IntentFilter();
        filter.addAction("android.accounts.LOGIN_ACCOUNTS_CHANGED");
        filter.addAction("android.accounts.action.ACCOUNT_REMOVED");
        filter.addAction("android.app.action.ACTION_PASSWORD_CHANGED");
        filter.addAction("android.app.action.ACTION_PASSWORD_EXPIRING");
        filter.addAction("android.app.action.ACTION_PASSWORD_FAILED");
        filter.addAction("android.app.action.ACTION_PASSWORD_SUCCEEDED");
        filter.addAction("android.app.action.AFFILIATED_PROFILE_TRANSFER_OWNERSHIP_COMPLETE");
        filter.addAction("android.app.action.APPLICATION_DELEGATION_SCOPES_CHANGED");
        filter.addAction("android.app.action.APP_BLOCK_STATE_CHANGED");
        filter.addAction("android.app.action.AUTOMATIC_ZEN_RULE_STATUS_CHANGED");
        filter.addAction("android.app.action.BUGREPORT_FAILED");
        filter.addAction("android.app.action.BUGREPORT_SHARE");
        filter.addAction("android.app.action.BUGREPORT_SHARING_DECLINED");
        filter.addAction("android.app.action.CLOSE_NOTIFICATION_HANDLER_PANEL");
        filter.addAction("android.app.action.COMPLIANCE_ACKNOWLEDGEMENT_REQUIRED");
        filter.addAction("android.app.action.DATA_SHARING_RESTRICTION_APPLIED");
        filter.addAction("android.app.action.DEVICE_ADMIN_DISABLED");
        filter.addAction("android.app.action.DEVICE_ADMIN_DISABLE_REQUESTED");
        filter.addAction("android.app.action.DEVICE_ADMIN_ENABLED");
        filter.addAction("android.app.action.DEVICE_OWNER_CHANGED");
        filter.addAction("android.app.action.DEVICE_POLICY_CONSTANTS_CHANGED");
        filter.addAction("android.app.action.DEVICE_POLICY_RESOURCE_UPDATED");
        filter.addAction("android.app.action.INTERRUPTION_FILTER_CHANGED");
        filter.addAction("android.app.action.INTERRUPTION_FILTER_CHANGED_INTERNAL");
        filter.addAction("android.app.action.LOCK_TASK_ENTERING");
        filter.addAction("android.app.action.LOCK_TASK_EXITING");
        filter.addAction("android.app.action.NETWORK_LOGS_AVAILABLE");
        filter.addAction("android.app.action.NEXT_ALARM_CLOCK_CHANGED");
        filter.addAction("android.app.action.NOTIFICATION_CHANNEL_BLOCK_STATE_CHANGED");
        filter.addAction("android.app.action.NOTIFICATION_CHANNEL_GROUP_BLOCK_STATE_CHANGED");
        filter.addAction("android.app.action.NOTIFICATION_LISTENER_ENABLED_CHANGED");
        filter.addAction("android.app.action.NOTIFICATION_POLICY_ACCESS_GRANTED_CHANGED");
        filter.addAction("android.app.action.NOTIFICATION_POLICY_CHANGED");
        filter.addAction("android.app.action.NOTIFY_PENDING_SYSTEM_UPDATE");
        filter.addAction("android.app.action.OPERATION_SAFETY_STATE_CHANGED");
        filter.addAction("android.app.action.PROFILE_OWNER_CHANGED");
        filter.addAction("android.app.action.PROFILE_PROVISIONING_COMPLETE");
        filter.addAction("android.app.action.PROVISIONING_COMPLETED");
        filter.addAction("android.app.action.SCHEDULE_EXACT_ALARM_PERMISSION_STATE_CHANGED");
        filter.addAction("android.app.action.SECURITY_LOGS_AVAILABLE");
        filter.addAction("android.app.action.SHOW_NEW_USER_DISCLAIMER");
        filter.addAction("android.app.action.SYSTEM_UPDATE_POLICY_CHANGED");
        filter.addAction("android.app.action.TRANSFER_OWNERSHIP_COMPLETE");
        filter.addAction("android.app.action.USER_ADDED");
        filter.addAction("android.app.action.USER_REMOVED");
        filter.addAction("android.app.action.USER_STARTED");
        filter.addAction("android.app.action.USER_STOPPED");
        filter.addAction("android.app.action.USER_SWITCHED");
        filter.addAction("android.appwidget.action.APPWIDGET_DELETED");
        filter.addAction("android.appwidget.action.APPWIDGET_DISABLED");
        filter.addAction("android.appwidget.action.APPWIDGET_ENABLED");
        filter.addAction("android.appwidget.action.APPWIDGET_HOST_RESTORED");
        filter.addAction("android.appwidget.action.APPWIDGET_RESTORED");
        filter.addAction("android.appwidget.action.APPWIDGET_UPDATE");
        filter.addAction("android.appwidget.action.APPWIDGET_UPDATE_OPTIONS");
        filter.addAction("android.bluetooth.a2dp.profile.action.CONNECTION_STATE_CHANGED");
        filter.addAction("android.bluetooth.a2dp.profile.action.PLAYING_STATE_CHANGED");
        filter.addAction("android.bluetooth.action.CSIS_CONNECTION_STATE_CHANGED");
        filter.addAction("android.bluetooth.action.LE_AUDIO_CONNECTION_STATE_CHANGED");
        filter.addAction("android.bluetooth.adapter.action.CONNECTION_STATE_CHANGED");
        filter.addAction("android.bluetooth.adapter.action.DISCOVERY_FINISHED");
        filter.addAction("android.bluetooth.adapter.action.DISCOVERY_STARTED");
        filter.addAction("android.bluetooth.adapter.action.LOCAL_NAME_CHANGED");
        filter.addAction("android.bluetooth.adapter.action.SCAN_MODE_CHANGED");
        filter.addAction("android.bluetooth.adapter.action.STATE_CHANGED");
        filter.addAction("android.bluetooth.device.action.ACL_CONNECTED");
        filter.addAction("android.bluetooth.device.action.ACL_DISCONNECTED");
        filter.addAction("android.bluetooth.device.action.ACL_DISCONNECT_REQUESTED");
        filter.addAction("android.bluetooth.device.action.ALIAS_CHANGED");
        filter.addAction("android.bluetooth.device.action.BOND_STATE_CHANGED");
        filter.addAction("android.bluetooth.device.action.CLASS_CHANGED");
        filter.addAction("android.bluetooth.device.action.FOUND");
        filter.addAction("android.bluetooth.device.action.NAME_CHANGED");
        filter.addAction("android.bluetooth.device.action.PAIRING_REQUEST");
        filter.addAction("android.bluetooth.device.action.UUID");
        filter.addAction("android.bluetooth.headset.action.VENDOR_SPECIFIC_HEADSET_EVENT");
        filter.addAction("android.bluetooth.headset.profile.action.AUDIO_STATE_CHANGED");
        filter.addAction("android.bluetooth.headset.profile.action.CONNECTION_STATE_CHANGED");
        filter.addAction("android.bluetooth.hearingaid.profile.action.CONNECTION_STATE_CHANGED");
        filter.addAction("android.bluetooth.hiddevice.profile.action.CONNECTION_STATE_CHANGED");
        filter.addAction("android.content.pm.action.SESSION_COMMITTED");
        filter.addAction("android.content.pm.action.SESSION_UPDATED");
        filter.addAction("android.hardware.action.NEW_PICTURE");
        filter.addAction("android.hardware.action.NEW_VIDEO");
        filter.addAction("android.hardware.hdmi.action.OSD_MESSAGE");
        filter.addAction("android.hardware.input.action.QUERY_KEYBOARD_LAYOUTS");
        filter.addAction("android.hardware.usb.action.USB_ACCESSORY_ATTACHED");
        filter.addAction("android.hardware.usb.action.USB_ACCESSORY_DETACHED");
        filter.addAction("android.hardware.usb.action.USB_ACCESSORY_HANDSHAKE");
        filter.addAction("android.hardware.usb.action.USB_DEVICE_ATTACHED");
        filter.addAction("android.hardware.usb.action.USB_DEVICE_DETACHED");
        filter.addAction("android.intent.action.ACTION_IDLE_MAINTENANCE_END");
        filter.addAction("android.intent.action.ACTION_IDLE_MAINTENANCE_START");
        filter.addAction("android.intent.action.ACTION_POWER_CONNECTED");
        filter.addAction("android.intent.action.ACTION_POWER_DISCONNECTED");
        filter.addAction("android.intent.action.ACTION_PREFERRED_ACTIVITY_CHANGED");
        filter.addAction("android.intent.action.ACTION_SHUTDOWN");
        filter.addAction("android.intent.action.AIRPLANE_MODE");
        filter.addAction("android.intent.action.ALARM_CHANGED");
        filter.addAction("android.intent.action.APPLICATION_LOCALE_CHANGED");
        filter.addAction("android.intent.action.APPLICATION_RESTRICTIONS_CHANGED");
        filter.addAction("android.intent.action.BATTERY_CHANGED");
        filter.addAction("android.intent.action.BATTERY_LOW");
        filter.addAction("android.intent.action.BATTERY_OKAY");
        filter.addAction("android.intent.action.BOOT_COMPLETED");
        filter.addAction("android.intent.action.CALL_DISCONNECT_CAUSE");
        filter.addAction("android.intent.action.CAMERA_BUTTON");
        filter.addAction("android.intent.action.CANCEL_ENABLE_ROLLBACK");
        filter.addAction("android.intent.action.CLOSE_SYSTEM_DIALOGS");
        filter.addAction("android.intent.action.CONFIGURATION_CHANGED");
        filter.addAction("android.intent.action.CONTENT_CHANGED");
        filter.addAction("android.intent.action.DATA_SMS_RECEIVED");
        filter.addAction("android.intent.action.DATA_STALL_DETECTED");
        filter.addAction("android.intent.action.DATE_CHANGED");
        filter.addAction("android.intent.action.DEVICE_STORAGE_FULL");
        filter.addAction("android.intent.action.DEVICE_STORAGE_LOW");
        filter.addAction("android.intent.action.DEVICE_STORAGE_NOT_FULL");
        filter.addAction("android.intent.action.DEVICE_STORAGE_OK");
        filter.addAction("android.intent.action.DISTRACTING_PACKAGES_CHANGED");
        filter.addAction("android.intent.action.DOCK_EVENT");
        filter.addAction("android.intent.action.DOMAINS_NEED_VERIFICATION");
        filter.addAction("android.intent.action.DOWNLOAD_COMPLETE");
        filter.addAction("android.intent.action.DOWNLOAD_NOTIFICATION_CLICKED");
        filter.addAction("android.intent.action.DREAMING_STARTED");
        filter.addAction("android.intent.action.DREAMING_STOPPED");
        filter.addAction("android.intent.action.DROPBOX_ENTRY_ADDED");
        filter.addAction("android.intent.action.DYNAMIC_SENSOR_CHANGED");
        filter.addAction("android.intent.action.EMERGENCY_CALLBACK_MODE_CHANGED");
        filter.addAction("android.intent.action.EMERGENCY_CALL_STATE_CHANGED");
        filter.addAction("android.intent.action.EXTERNAL_APPLICATIONS_AVAILABLE");
        filter.addAction("android.intent.action.EXTERNAL_APPLICATIONS_UNAVAILABLE");
        filter.addAction("android.intent.action.FACTORY_RESET");
        filter.addAction("android.intent.action.FETCH_VOICEMAIL");
        filter.addAction("android.intent.action.GTALK_CONNECTED");
        filter.addAction("android.intent.action.GTALK_DISCONNECTED");
        filter.addAction("android.intent.action.HEADSET_PLUG");
        filter.addAction("android.intent.action.HEADSET_PLUG");
        filter.addAction("android.intent.action.INPUT_METHOD_CHANGED");
        filter.addAction("android.intent.action.INTENT_FILTER_NEEDS_VERIFICATION");
        filter.addAction("android.intent.action.LOCALE_CHANGED");
        filter.addAction("android.intent.action.LOCKED_BOOT_COMPLETED");
        filter.addAction("android.intent.action.MANAGE_PACKAGE_STORAGE");
        filter.addAction("android.intent.action.MASTER_CLEAR_NOTIFICATION");
        filter.addAction("android.intent.action.MEDIA_BAD_REMOVAL");
        filter.addAction("android.intent.action.MEDIA_BUTTON");
        filter.addAction("android.intent.action.MEDIA_CHECKING");
        filter.addAction("android.intent.action.MEDIA_EJECT");
        filter.addAction("android.intent.action.MEDIA_MOUNTED");
        filter.addAction("android.intent.action.MEDIA_NOFS");
        filter.addAction("android.intent.action.MEDIA_REMOVED");
        filter.addAction("android.intent.action.MEDIA_SCANNER_FINISHED");
        filter.addAction("android.intent.action.MEDIA_SCANNER_SCAN_FILE");
        filter.addAction("android.intent.action.MEDIA_SCANNER_STARTED");
        filter.addAction("android.intent.action.MEDIA_SHARED");
        filter.addAction("android.intent.action.MEDIA_UNMOUNTABLE");
        filter.addAction("android.intent.action.MEDIA_UNMOUNTED");
        filter.addAction("android.intent.action.MY_PACKAGE_REPLACED");
        filter.addAction("android.intent.action.MY_PACKAGE_SUSPENDED");
        filter.addAction("android.intent.action.MY_PACKAGE_UNSUSPENDED");
        filter.addAction("android.intent.action.NEW_OUTGOING_CALL");
        filter.addAction("android.intent.action.NEW_VOICEMAIL");
        filter.addAction("android.intent.action.PACKAGES_SUSPENDED");
        filter.addAction("android.intent.action.PACKAGES_SUSPENSION_CHANGED");
        filter.addAction("android.intent.action.PACKAGES_UNSUSPENDED");
        filter.addAction("android.intent.action.PACKAGE_ADDED");
        filter.addAction("android.intent.action.PACKAGE_CHANGED");
        filter.addAction("android.intent.action.PACKAGE_DATA_CLEARED");
        filter.addAction("android.intent.action.PACKAGE_ENABLE_ROLLBACK");
        filter.addAction("android.intent.action.PACKAGE_FIRST_LAUNCH");
        filter.addAction("android.intent.action.PACKAGE_FULLY_REMOVED");
        filter.addAction("android.intent.action.PACKAGE_INSTALL");
        filter.addAction("android.intent.action.PACKAGE_NEEDS_INTEGRITY_VERIFICATION");
        filter.addAction("android.intent.action.PACKAGE_NEEDS_VERIFICATION");
        filter.addAction("android.intent.action.PACKAGE_REMOVED");
        filter.addAction("android.intent.action.PACKAGE_REMOVED_INTERNAL");
        filter.addAction("android.intent.action.PACKAGE_REPLACED");
        filter.addAction("android.intent.action.PACKAGE_RESTARTED");
        filter.addAction("android.intent.action.PACKAGE_UNSUSPENDED_MANUALLY");
        filter.addAction("android.intent.action.PACKAGE_VERIFIED");
        filter.addAction("android.intent.action.PHONE_STATE");
        filter.addAction("android.intent.action.PROVIDER_CHANGED");
        filter.addAction("android.intent.action.PROXY_CHANGE");
        filter.addAction("android.intent.action.QUERY_PACKAGE_RESTART");
        filter.addAction("android.intent.action.REBOOT");
        filter.addAction("android.intent.action.ROLLBACK_COMMITTED");
        filter.addAction("android.intent.action.SCREEN_OFF");
        filter.addAction("android.intent.action.SCREEN_ON");
        filter.addAction("android.intent.action.SERVICE_STATE");
        filter.addAction("android.intent.action.SIM_STATE_CHANGED");
        filter.addAction("android.intent.action.SPLIT_CONFIGURATION_CHANGED");
        filter.addAction("android.intent.action.SUB_DEFAULT_CHANGED");
        filter.addAction("android.intent.action.TIMEZONE_CHANGED");
        filter.addAction("android.intent.action.TIME_SET");
        filter.addAction("android.intent.action.TIME_TICK");
        filter.addAction("android.intent.action.UID_REMOVED");
        filter.addAction("android.intent.action.UMS_CONNECTED");
        filter.addAction("android.intent.action.UMS_DISCONNECTED");
        filter.addAction("android.intent.action.USER_PRESENT");
        filter.addAction("android.intent.action.USER_UNLOCKED");
        filter.addAction("android.intent.action.WALLPAPER_CHANGED");
        filter.addAction("android.location.MODE_CHANGED");
        filter.addAction("android.location.PROVIDERS_CHANGED");
        filter.addAction("android.location.action.ADAS_GNSS_ENABLED_CHANGED");
        filter.addAction("android.location.action.GNSS_CAPABILITIES_CHANGED");
        filter.addAction("android.media.ACTION_SCO_AUDIO_STATE_UPDATED");
        filter.addAction("android.media.AUDIO_BECOMING_NOISY");
        filter.addAction("android.media.INTERNAL_RINGER_MODE_CHANGED_ACTION");
        filter.addAction("android.media.MASTER_MUTE_CHANGED_ACTION");
        filter.addAction("android.media.RINGER_MODE_CHANGED");
        filter.addAction("android.media.SCO_AUDIO_STATE_CHANGED");
        filter.addAction("android.media.STREAM_DEVICES_CHANGED_ACTION");
        filter.addAction("android.media.STREAM_MUTE_CHANGED_ACTION");
        filter.addAction("android.media.VIBRATE_SETTING_CHANGED");
        filter.addAction("android.media.VOLUME_CHANGED_ACTION");
        filter.addAction("android.media.VOLUME_CHANGED_ACTION");
        filter.addAction("android.media.action.CLOSE_AUDIO_EFFECT_CONTROL_SESSION");
        filter.addAction("android.media.action.HDMI_AUDIO_PLUG");
        filter.addAction("android.media.action.MICROPHONE_MUTE_CHANGED");
        filter.addAction("android.media.action.OPEN_AUDIO_EFFECT_CONTROL_SESSION");
        filter.addAction("android.media.action.SPEAKERPHONE_STATE_CHANGED");
        filter.addAction("android.media.tv.action.CHANNEL_BROWSABLE_REQUESTED");
        filter.addAction("android.media.tv.action.INITIALIZE_PROGRAMS");
        filter.addAction("android.media.tv.action.PREVIEW_PROGRAM_ADDED_TO_WATCH_NEXT");
        filter.addAction("android.media.tv.action.PREVIEW_PROGRAM_BROWSABLE_DISABLED");
        filter.addAction("android.media.tv.action.WATCH_NEXT_PROGRAM_BROWSABLE_DISABLED");
        filter.addAction("android.net.conn.BACKGROUND_DATA_SETTING_CHANGED");
        filter.addAction("android.net.conn.CONNECTIVITY_CHANGE");
        filter.addAction("android.net.conn.RESTRICT_BACKGROUND_CHANGED");
        filter.addAction("android.net.nsd.STATE_CHANGED");
        filter.addAction("android.net.scoring.SCORER_CHANGED");
        filter.addAction("android.net.scoring.SCORE_NETWORKS");
        filter.addAction("android.net.sip.action.SIP_CALL_OPTION_CHANGED");
        filter.addAction("android.net.sip.action.SIP_INCOMING_CALL");
        filter.addAction("android.net.sip.action.SIP_REMOVE_PROFILE");
        filter.addAction("android.net.sip.action.SIP_SERVICE_UP");
        filter.addAction("android.net.sip.action.START_SIP");
        filter.addAction("android.net.wifi.NETWORK_IDS_CHANGED");
        filter.addAction("android.net.wifi.RSSI_CHANGED");
        filter.addAction("android.net.wifi.SCAN_RESULTS");
        filter.addAction("android.net.wifi.STATE_CHANGE");
        filter.addAction("android.net.wifi.WIFI_STATE_CHANGED");
        filter.addAction("android.net.wifi.action.WIFI_NETWORK_SUGGESTION_POST_CONNECTION");
        filter.addAction("android.net.wifi.action.WIFI_SCAN_AVAILABILITY_CHANGED");
        filter.addAction("android.net.wifi.aware.action.WIFI_AWARE_RESOURCE_CHANGED");
        filter.addAction("android.net.wifi.aware.action.WIFI_AWARE_STATE_CHANGED");
        filter.addAction("android.net.wifi.p2p.CONNECTION_STATE_CHANGE");
        filter.addAction("android.net.wifi.p2p.DISCOVERY_STATE_CHANGE");
        filter.addAction("android.net.wifi.p2p.PEERS_CHANGED");
        filter.addAction("android.net.wifi.p2p.STATE_CHANGED");
        filter.addAction("android.net.wifi.p2p.THIS_DEVICE_CHANGED");
        filter.addAction("android.net.wifi.rtt.action.WIFI_RTT_STATE_CHANGED");
        filter.addAction("android.net.wifi.supplicant.CONNECTION_CHANGE");
        filter.addAction("android.net.wifi.supplicant.STATE_CHANGE");
        filter.addAction("android.nfc.action.ADAPTER_STATE_CHANGED");
        filter.addAction("android.nfc.action.PREFERRED_PAYMENT_CHANGED");
        filter.addAction("android.nfc.action.TRANSACTION_DETECTED");
        filter.addAction("android.os.action.ACTION_EFFECTS_SUPPRESSOR_CHANGED");
        filter.addAction("android.os.action.DEVICE_IDLE_MODE_CHANGED");
        filter.addAction("android.os.action.ENHANCED_DISCHARGE_PREDICTION_CHANGED");
        filter.addAction("android.os.action.LIGHT_DEVICE_IDLE_MODE_CHANGED");
        filter.addAction("android.os.action.LIGHT_DEVICE_IDLE_MODE_CHANGED");
        filter.addAction("android.os.action.LOW_POWER_STANDBY_ENABLED_CHANGED");
        filter.addAction("android.os.action.POWER_SAVE_MODE_CHANGED");
        filter.addAction("android.os.action.POWER_SAVE_MODE_CHANGED_INTERNAL");
        filter.addAction("android.os.action.POWER_SAVE_TEMP_WHITELIST_CHANGED");
        filter.addAction("android.os.action.POWER_SAVE_WHITELIST_CHANGED");
        filter.addAction("android.os.action.UPDATE_EMERGENCY_NUMBER_DB");
        filter.addAction("android.provider.Telephony.MMS_DOWNLOADED");
        filter.addAction("android.provider.Telephony.SECRET_CODE");
        filter.addAction("android.provider.Telephony.SIM_FULL");
        filter.addAction("android.provider.Telephony.SMS_CARRIER_PROVISION");
        filter.addAction("android.provider.Telephony.SMS_CB_RECEIVED");
        filter.addAction("android.provider.Telephony.SMS_DELIVER");
        filter.addAction("android.provider.Telephony.SMS_RECEIVED");
        filter.addAction("android.provider.Telephony.SMS_REJECTED");
        filter.addAction("android.provider.Telephony.SMS_SERVICE_CATEGORY_PROGRAM_DATA_RECEIVED");
        filter.addAction("android.provider.Telephony.WAP_PUSH_DELIVER");
        filter.addAction("android.provider.Telephony.WAP_PUSH_RECEIVED");
        filter.addAction("android.provider.action.DEFAULT_SMS_PACKAGE_CHANGED");
        filter.addAction("android.provider.action.EXTERNAL_PROVIDER_CHANGE");
        filter.addAction("android.provider.action.SIM_ACCOUNTS_CHANGED");
        filter.addAction("android.provider.action.SMS_EMERGENCY_CB_RECEIVED");
        filter.addAction("android.provider.action.SMS_MMS_DB_CREATED");
        filter.addAction("android.provider.action.SMS_MMS_DB_LOST");
        filter.addAction("android.provider.action.SYNC_VOICEMAIL");
        filter.addAction("android.se.omapi.action.SECURE_ELEMENT_STATE_CHANGED");
        filter.addAction("android.security.STORAGE_CHANGED");
        filter.addAction("android.security.action.KEYCHAIN_CHANGED");
        filter.addAction("android.security.action.KEY_ACCESS_CHANGED");
        filter.addAction("android.security.action.TRUST_STORE_CHANGED");
        filter.addAction("android.service.controls.action.ADD_CONTROL");
        filter.addAction("android.settings.ENABLE_MMS_DATA_REQUEST");
        filter.addAction("android.settings.SHOW_RESTRICTED_SETTING_DIALOG");
        filter.addAction("android.speech.tts.TTS_QUEUE_PROCESSING_COMPLETED");
        filter.addAction("android.speech.tts.engine.TTS_DATA_INSTALLED");
        filter.addAction("android.telephony.action.AREA_INFO_UPDATED");
        filter.addAction("android.telephony.action.CARRIER_SIGNAL_DEFAULT_NETWORK_AVAILABLE");
        filter.addAction("android.telephony.action.CARRIER_SIGNAL_PCO_VALUE");
        filter.addAction("android.telephony.action.CARRIER_SIGNAL_REDIRECTED");
        filter.addAction("android.telephony.action.CARRIER_SIGNAL_REQUEST_NETWORK_FAILED");
        filter.addAction("android.telephony.action.CARRIER_SIGNAL_RESET");
        filter.addAction("android.telephony.action.DEFAULT_SMS_SUBSCRIPTION_CHANGED");
        filter.addAction("android.telephony.action.DEFAULT_SUBSCRIPTION_CHANGED");
        filter.addAction("android.telephony.action.PRIMARY_SUBSCRIPTION_LIST_CHANGED");
        filter.addAction("android.telephony.action.REFRESH_SUBSCRIPTION_PLANS");
        filter.addAction("android.telephony.action.SECRET_CODE");
        filter.addAction("android.telephony.action.SERVICE_PROVIDERS_UPDATED");
        filter.addAction("android.telephony.action.SIM_APPLICATION_STATE_CHANGED");
        filter.addAction("android.telephony.action.SIM_CARD_STATE_CHANGED");
        filter.addAction("android.telephony.action.SIM_SLOT_STATUS_CHANGED");
        filter.addAction("android.telephony.action.SUBSCRIPTION_CARRIER_IDENTITY_CHANGED");
        filter.addAction("android.telephony.action.SUBSCRIPTION_PLANS_CHANGED");
        filter.addAction("android.telephony.action.SUBSCRIPTION_SPECIFIC_CARRIER_IDENTITY_CHANGED");
        filter.addAction("android.telephony.euicc.action.NOTIFY_CARRIER_SETUP_INCOMPLETE");
        filter.addAction("android.telephony.euicc.action.OTA_STATUS_CHANGED");
        filter.addAction("android.telephony.ims.action.RCS_SINGLE_REGISTRATION_CAPABILITY_UPDATE");
        filter.addAction("android.telephony.ims.action.WFC_IMS_REGISTRATION_ERROR");
        filter.addAction("com.android.intent.action.DISMISS_KEYBOARD_SHORTCUTS");
        filter.addAction("com.android.intent.action.SHOW_KEYBOARD_SHORTCUTS");
        filter.addAction("com.android.internal.intent.action.ACTION_FORBIDDEN_NO_SERVICE_AUTHORIZATION");
        filter.addAction("com.android.internal.provider.action.VOICEMAIL_SMS_RECEIVED");


        registerReceiver(receiver, filter);
    }

    @Override
    public void onDestroy() {
        super.onDestroy();
        unregisterReceiver(receiver);
    }


    @Nullable
    @Override
    public IBinder onBind(Intent intent) {
        return null;
    }
}
